[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
rustflags = [ "-C", "link-args=-Tlink.x"]
runner = "qemu-system-arm -s -S -cpu cortex-m3 --machine stm32vldiscovery -nographic --kernel "

