title: Rust Embedded 
description: >
  Please star my repository if you find it helpful.

author: Rohit Patil

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
