title: Rust Embedded
author: 
  name: Rohit Patil

description:
  This will help you to understand how to use Rust in Embedded.
  If you like my work, please go to [repository](https://github.com/RohitPatil555/Rust-Embedded) and click on *Star button* at top right corner.

theme: minima

header_pages:
  index.md

minima:
  skin: dark