title: Rust Embedded
author: 
  name: Rohit Patil

description: >
  Please star my repository if you find it helpful.

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: dark
  social_links:
  - { platform: github, user_url: "https://github.com/RohitPatil555/Rust-Embedded" }